### ISSUE TITLE
Include information on found bugs (by runtimes such as Valgrind) in the .json file

### ISSUE THREAD

**Issue by mrigger** [jku-ssw/benchmarks#8]
Some bug-finding tools detect bugs in the benchmarks. It would be desirable to detect such instances (e.g., by checking `stderr`) and recording them in the `.json` file. Then, we could also compare the bug-finding capabilities of various runtimes.

**Comment by pointhi** [comment]
I found out it is a bit hard with the current datamodel to do it.

The tool uses the internal benchmark name to specify which key the benchmark gets (because we can have multiple benchmarks per file).

stderr on the other side is specific for a file, and we probably don't know the actual names of the benchmarks which are failing. Probably the best way would be to add a new dictionary in the bench file containing the harnesses and their output.

**Comment by pointhi** [comment]
Proposal:

```json
{
  "output": {
    "harness_name": {
      "runtime_name": [
        {"stdout": "...", "stderr": "..."}
      ]
    }
  },
  "data": {
    "harness_name": {
      "runtime_name": [
        {"harness": "harness_name"}
     ] 
    }
  }
}
```

Problems: linking between harness and run. Could be solved with an UUID, or simply be ignored if not important
